// Code generated by goctl. DO NOT EDIT!
// Source: filesys.proto

package filesysclient

import (
	"context"

	"recorder/service/file_sys/cmd/rpc/filesys"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	StorePartlyReq  = filesys.StorePartlyReq
	StorePartlyResp = filesys.StorePartlyResp

	FileSys interface {
		StorePartly(ctx context.Context, in *StorePartlyReq, opts ...grpc.CallOption) (*StorePartlyResp, error)
	}

	defaultFileSys struct {
		cli zrpc.Client
	}
)

func NewFileSys(cli zrpc.Client) FileSys {
	return &defaultFileSys{
		cli: cli,
	}
}

func (m *defaultFileSys) StorePartly(ctx context.Context, in *StorePartlyReq, opts ...grpc.CallOption) (*StorePartlyResp, error) {
	client := filesys.NewFileSysClient(m.cli.Conn())
	return client.StorePartly(ctx, in, opts...)
}
