// Code generated by goctl. DO NOT EDIT!
// Source: filesys.proto

package server

import (
	"context"

	"recorder/service/file_sys/cmd/rpc/filesys"
	"recorder/service/file_sys/cmd/rpc/internal/logic"
	"recorder/service/file_sys/cmd/rpc/internal/svc"
)

type FileSysServer struct {
	svcCtx *svc.ServiceContext
}

func NewFileSysServer(svcCtx *svc.ServiceContext) *FileSysServer {
	return &FileSysServer{
		svcCtx: svcCtx,
	}
}

func (s *FileSysServer) StorePartly(ctx context.Context, in *filesys.StorePartlyReq) (*filesys.StorePartlyResp, error) {
	l := logic.NewStorePartlyLogic(ctx, s.svcCtx)
	return l.StorePartly(in)
}
