// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"recorder/service/gateway/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/video/upload/conn",
				Handler: uploadConnHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/video/upload/:id/:chunk",
				Handler: uploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/video/download/:id/:chunk",
				Handler: downloadHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
