// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filesys.proto

package filesys

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorePartlyReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename             string   `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Chunk                int64    `protobuf:"varint,5,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Chunks               int64    `protobuf:"varint,6,opt,name=chunks,proto3" json:"chunks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePartlyReq) Reset()         { *m = StorePartlyReq{} }
func (m *StorePartlyReq) String() string { return proto.CompactTextString(m) }
func (*StorePartlyReq) ProtoMessage()    {}
func (*StorePartlyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab43d0115fee6550, []int{0}
}

func (m *StorePartlyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePartlyReq.Unmarshal(m, b)
}
func (m *StorePartlyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePartlyReq.Marshal(b, m, deterministic)
}
func (m *StorePartlyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePartlyReq.Merge(m, src)
}
func (m *StorePartlyReq) XXX_Size() int {
	return xxx_messageInfo_StorePartlyReq.Size(m)
}
func (m *StorePartlyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePartlyReq.DiscardUnknown(m)
}

var xxx_messageInfo_StorePartlyReq proto.InternalMessageInfo

func (m *StorePartlyReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *StorePartlyReq) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *StorePartlyReq) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *StorePartlyReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StorePartlyReq) GetChunk() int64 {
	if m != nil {
		return m.Chunk
	}
	return 0
}

func (m *StorePartlyReq) GetChunks() int64 {
	if m != nil {
		return m.Chunks
	}
	return 0
}

type StorePartlyResp struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsFinished           bool     `protobuf:"varint,2,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorePartlyResp) Reset()         { *m = StorePartlyResp{} }
func (m *StorePartlyResp) String() string { return proto.CompactTextString(m) }
func (*StorePartlyResp) ProtoMessage()    {}
func (*StorePartlyResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab43d0115fee6550, []int{1}
}

func (m *StorePartlyResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorePartlyResp.Unmarshal(m, b)
}
func (m *StorePartlyResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorePartlyResp.Marshal(b, m, deterministic)
}
func (m *StorePartlyResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorePartlyResp.Merge(m, src)
}
func (m *StorePartlyResp) XXX_Size() int {
	return xxx_messageInfo_StorePartlyResp.Size(m)
}
func (m *StorePartlyResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StorePartlyResp.DiscardUnknown(m)
}

var xxx_messageInfo_StorePartlyResp proto.InternalMessageInfo

func (m *StorePartlyResp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *StorePartlyResp) GetIsFinished() bool {
	if m != nil {
		return m.IsFinished
	}
	return false
}

func init() {
	proto.RegisterType((*StorePartlyReq)(nil), "filesys.storePartlyReq")
	proto.RegisterType((*StorePartlyResp)(nil), "filesys.storePartlyResp")
}

func init() { proto.RegisterFile("filesys.proto", fileDescriptor_ab43d0115fee6550) }

var fileDescriptor_ab43d0115fee6550 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x59, 0xdb, 0xa6, 0xcd, 0xd4, 0x3f, 0x30, 0x88, 0x5d, 0x0a, 0x62, 0xe8, 0x29, 0xa7,
	0x1e, 0xf4, 0x0b, 0xa8, 0x87, 0x82, 0x78, 0x91, 0xf5, 0xe6, 0x25, 0xac, 0xdd, 0x2d, 0x59, 0xac,
	0xc9, 0xba, 0xb3, 0x3d, 0xe4, 0x0b, 0xf9, 0x39, 0x25, 0x93, 0x54, 0x0c, 0x78, 0x7b, 0xbf, 0x19,
	0x76, 0xde, 0xdb, 0x07, 0x67, 0x3b, 0xb7, 0xb7, 0xd4, 0xd0, 0xda, 0x87, 0x3a, 0xd6, 0x38, 0xed,
	0x71, 0xf5, 0x2d, 0xe0, 0x9c, 0x62, 0x1d, 0xec, 0x8b, 0x0e, 0x71, 0xdf, 0x28, 0xfb, 0x85, 0x0b,
	0x98, 0x1e, 0xc8, 0x86, 0xc2, 0x19, 0x29, 0x32, 0x91, 0x8f, 0x54, 0xd2, 0xe2, 0x93, 0xc1, 0x25,
	0xcc, 0xda, 0x67, 0x95, 0xfe, 0xb4, 0xf2, 0x24, 0x13, 0x79, 0xaa, 0x7e, 0x19, 0xaf, 0x01, 0xb6,
	0xc1, 0xea, 0x68, 0x4d, 0xa1, 0xa3, 0x1c, 0xf1, 0x36, 0xed, 0x27, 0x0f, 0x11, 0x11, 0xc6, 0x46,
	0x47, 0x2d, 0xc7, 0x99, 0xc8, 0x4f, 0x15, 0x6b, 0xbc, 0x84, 0xc9, 0xb6, 0x3c, 0x54, 0x1f, 0x72,
	0xc2, 0x2e, 0x1d, 0xe0, 0x15, 0x24, 0x2c, 0x48, 0x26, 0x9d, 0x79, 0x47, 0xab, 0x0d, 0x5c, 0x0c,
	0x72, 0x92, 0x6f, 0x8f, 0x7a, 0x1d, 0x4b, 0x4e, 0x99, 0x2a, 0xd6, 0x78, 0x03, 0x73, 0x47, 0xc5,
	0xce, 0x55, 0x8e, 0x4a, 0x6b, 0x38, 0xe6, 0x4c, 0x81, 0xa3, 0x4d, 0x3f, 0xb9, 0x7d, 0x06, 0xfe,
	0xfb, 0x6b, 0x43, 0x78, 0x0f, 0xf3, 0x3f, 0x27, 0x71, 0xb1, 0x3e, 0x76, 0x34, 0x2c, 0x64, 0x29,
	0xff, 0x5f, 0x90, 0x7f, 0x4c, 0xdf, 0x8e, 0x45, 0xbe, 0x27, 0x5c, 0xec, 0xdd, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xbc, 0x1f, 0xb4, 0x0f, 0x69, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileSysClient is the client API for FileSys service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileSysClient interface {
	StorePartly(ctx context.Context, in *StorePartlyReq, opts ...grpc.CallOption) (*StorePartlyResp, error)
}

type fileSysClient struct {
	cc *grpc.ClientConn
}

func NewFileSysClient(cc *grpc.ClientConn) FileSysClient {
	return &fileSysClient{cc}
}

func (c *fileSysClient) StorePartly(ctx context.Context, in *StorePartlyReq, opts ...grpc.CallOption) (*StorePartlyResp, error) {
	out := new(StorePartlyResp)
	err := c.cc.Invoke(ctx, "/filesys.fileSys/storePartly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileSysServer is the server API for FileSys service.
type FileSysServer interface {
	StorePartly(context.Context, *StorePartlyReq) (*StorePartlyResp, error)
}

// UnimplementedFileSysServer can be embedded to have forward compatible implementations.
type UnimplementedFileSysServer struct {
}

func (*UnimplementedFileSysServer) StorePartly(ctx context.Context, req *StorePartlyReq) (*StorePartlyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StorePartly not implemented")
}

func RegisterFileSysServer(s *grpc.Server, srv FileSysServer) {
	s.RegisterService(&_FileSys_serviceDesc, srv)
}

func _FileSys_StorePartly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePartlyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileSysServer).StorePartly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/filesys.fileSys/StorePartly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileSysServer).StorePartly(ctx, req.(*StorePartlyReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileSys_serviceDesc = grpc.ServiceDesc{
	ServiceName: "filesys.fileSys",
	HandlerType: (*FileSysServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "storePartly",
			Handler:    _FileSys_StorePartly_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "filesys.proto",
}
