// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video.proto

package video

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadingReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoName            string   `protobuf:"bytes,2,opt,name=video_name,json=videoName,proto3" json:"video_name,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadingReq) Reset()         { *m = UploadingReq{} }
func (m *UploadingReq) String() string { return proto.CompactTextString(m) }
func (*UploadingReq) ProtoMessage()    {}
func (*UploadingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}

func (m *UploadingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadingReq.Unmarshal(m, b)
}
func (m *UploadingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadingReq.Marshal(b, m, deterministic)
}
func (m *UploadingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadingReq.Merge(m, src)
}
func (m *UploadingReq) XXX_Size() int {
	return xxx_messageInfo_UploadingReq.Size(m)
}
func (m *UploadingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadingReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadingReq proto.InternalMessageInfo

func (m *UploadingReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UploadingReq) GetVideoName() string {
	if m != nil {
		return m.VideoName
	}
	return ""
}

func (m *UploadingReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type UploadingResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadingResp) Reset()         { *m = UploadingResp{} }
func (m *UploadingResp) String() string { return proto.CompactTextString(m) }
func (*UploadingResp) ProtoMessage()    {}
func (*UploadingResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{1}
}

func (m *UploadingResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadingResp.Unmarshal(m, b)
}
func (m *UploadingResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadingResp.Marshal(b, m, deterministic)
}
func (m *UploadingResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadingResp.Merge(m, src)
}
func (m *UploadingResp) XXX_Size() int {
	return xxx_messageInfo_UploadingResp.Size(m)
}
func (m *UploadingResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadingResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadingResp proto.InternalMessageInfo

func (m *UploadingResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *UploadingResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UploadedReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoName            string   `protobuf:"bytes,2,opt,name=video_name,json=videoName,proto3" json:"video_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadedReq) Reset()         { *m = UploadedReq{} }
func (m *UploadedReq) String() string { return proto.CompactTextString(m) }
func (*UploadedReq) ProtoMessage()    {}
func (*UploadedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{2}
}

func (m *UploadedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadedReq.Unmarshal(m, b)
}
func (m *UploadedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadedReq.Marshal(b, m, deterministic)
}
func (m *UploadedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadedReq.Merge(m, src)
}
func (m *UploadedReq) XXX_Size() int {
	return xxx_messageInfo_UploadedReq.Size(m)
}
func (m *UploadedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadedReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadedReq proto.InternalMessageInfo

func (m *UploadedReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UploadedReq) GetVideoName() string {
	if m != nil {
		return m.VideoName
	}
	return ""
}

type UploadedResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadedResp) Reset()         { *m = UploadedResp{} }
func (m *UploadedResp) String() string { return proto.CompactTextString(m) }
func (*UploadedResp) ProtoMessage()    {}
func (*UploadedResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{3}
}

func (m *UploadedResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadedResp.Unmarshal(m, b)
}
func (m *UploadedResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadedResp.Marshal(b, m, deterministic)
}
func (m *UploadedResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadedResp.Merge(m, src)
}
func (m *UploadedResp) XXX_Size() int {
	return xxx_messageInfo_UploadedResp.Size(m)
}
func (m *UploadedResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadedResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadedResp proto.InternalMessageInfo

func (m *UploadedResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetVideoListReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoListReq) Reset()         { *m = GetVideoListReq{} }
func (m *GetVideoListReq) String() string { return proto.CompactTextString(m) }
func (*GetVideoListReq) ProtoMessage()    {}
func (*GetVideoListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{4}
}

func (m *GetVideoListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoListReq.Unmarshal(m, b)
}
func (m *GetVideoListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoListReq.Marshal(b, m, deterministic)
}
func (m *GetVideoListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoListReq.Merge(m, src)
}
func (m *GetVideoListReq) XXX_Size() int {
	return xxx_messageInfo_GetVideoListReq.Size(m)
}
func (m *GetVideoListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoListReq proto.InternalMessageInfo

func (m *GetVideoListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetVideoListReq) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetVideoListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetVideoListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type GetVideoListResp struct {
	List                 []*GetVideoListRespVideoItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalPages           int64                        `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalCount           int64                        `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetVideoListResp) Reset()         { *m = GetVideoListResp{} }
func (m *GetVideoListResp) String() string { return proto.CompactTextString(m) }
func (*GetVideoListResp) ProtoMessage()    {}
func (*GetVideoListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5}
}

func (m *GetVideoListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoListResp.Unmarshal(m, b)
}
func (m *GetVideoListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoListResp.Marshal(b, m, deterministic)
}
func (m *GetVideoListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoListResp.Merge(m, src)
}
func (m *GetVideoListResp) XXX_Size() int {
	return xxx_messageInfo_GetVideoListResp.Size(m)
}
func (m *GetVideoListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoListResp proto.InternalMessageInfo

func (m *GetVideoListResp) GetList() []*GetVideoListRespVideoItem {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetVideoListResp) GetTotalPages() int64 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *GetVideoListResp) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type GetVideoListRespVideoItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoListRespVideoItem) Reset()         { *m = GetVideoListRespVideoItem{} }
func (m *GetVideoListRespVideoItem) String() string { return proto.CompactTextString(m) }
func (*GetVideoListRespVideoItem) ProtoMessage()    {}
func (*GetVideoListRespVideoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5, 0}
}

func (m *GetVideoListRespVideoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoListRespVideoItem.Unmarshal(m, b)
}
func (m *GetVideoListRespVideoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoListRespVideoItem.Marshal(b, m, deterministic)
}
func (m *GetVideoListRespVideoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoListRespVideoItem.Merge(m, src)
}
func (m *GetVideoListRespVideoItem) XXX_Size() int {
	return xxx_messageInfo_GetVideoListRespVideoItem.Size(m)
}
func (m *GetVideoListRespVideoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoListRespVideoItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoListRespVideoItem proto.InternalMessageInfo

func (m *GetVideoListRespVideoItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetVideoListRespVideoItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{6}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResp) Reset()         { *m = DeleteResp{} }
func (m *DeleteResp) String() string { return proto.CompactTextString(m) }
func (*DeleteResp) ProtoMessage()    {}
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{7}
}

func (m *DeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp.Unmarshal(m, b)
}
func (m *DeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp.Marshal(b, m, deterministic)
}
func (m *DeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp.Merge(m, src)
}
func (m *DeleteResp) XXX_Size() int {
	return xxx_messageInfo_DeleteResp.Size(m)
}
func (m *DeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp proto.InternalMessageInfo

func (m *DeleteResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetOneReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneReq) Reset()         { *m = GetOneReq{} }
func (m *GetOneReq) String() string { return proto.CompactTextString(m) }
func (*GetOneReq) ProtoMessage()    {}
func (*GetOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{8}
}

func (m *GetOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneReq.Unmarshal(m, b)
}
func (m *GetOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneReq.Marshal(b, m, deterministic)
}
func (m *GetOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneReq.Merge(m, src)
}
func (m *GetOneReq) XXX_Size() int {
	return xxx_messageInfo_GetOneReq.Size(m)
}
func (m *GetOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneReq proto.InternalMessageInfo

func (m *GetOneReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetOneReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetOneResp struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FinishedAt           string   `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneResp) Reset()         { *m = GetOneResp{} }
func (m *GetOneResp) String() string { return proto.CompactTextString(m) }
func (*GetOneResp) ProtoMessage()    {}
func (*GetOneResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{9}
}

func (m *GetOneResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneResp.Unmarshal(m, b)
}
func (m *GetOneResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneResp.Marshal(b, m, deterministic)
}
func (m *GetOneResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneResp.Merge(m, src)
}
func (m *GetOneResp) XXX_Size() int {
	return xxx_messageInfo_GetOneResp.Size(m)
}
func (m *GetOneResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneResp proto.InternalMessageInfo

func (m *GetOneResp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetOneResp) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetOneResp) GetFinishedAt() string {
	if m != nil {
		return m.FinishedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*UploadingReq)(nil), "video.uploadingReq")
	proto.RegisterType((*UploadingResp)(nil), "video.uploadingResp")
	proto.RegisterType((*UploadedReq)(nil), "video.uploadedReq")
	proto.RegisterType((*UploadedResp)(nil), "video.uploadedResp")
	proto.RegisterType((*GetVideoListReq)(nil), "video.getVideoListReq")
	proto.RegisterType((*GetVideoListResp)(nil), "video.getVideoListResp")
	proto.RegisterType((*GetVideoListRespVideoItem)(nil), "video.getVideoListResp.videoItem")
	proto.RegisterType((*DeleteReq)(nil), "video.deleteReq")
	proto.RegisterType((*DeleteResp)(nil), "video.deleteResp")
	proto.RegisterType((*GetOneReq)(nil), "video.getOneReq")
	proto.RegisterType((*GetOneResp)(nil), "video.getOneResp")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xed, 0x90, 0xc6, 0xe3, 0x02, 0x65, 0x8a, 0xa8, 0xe5, 0x02, 0x0d, 0x7b, 0xca, 0x85,
	0x56, 0x6a, 0x05, 0xe2, 0x86, 0x0a, 0xe2, 0x50, 0x09, 0x01, 0x32, 0x12, 0x87, 0x5e, 0x8c, 0xe9,
	0x0e, 0xe9, 0xaa, 0x89, 0x77, 0x9b, 0xdd, 0x70, 0xc8, 0x6f, 0xf0, 0x3b, 0x7c, 0x1c, 0xda, 0x5d,
	0xdb, 0x71, 0x93, 0x40, 0x0f, 0x3d, 0x65, 0xf7, 0xcd, 0x9b, 0x19, 0xcf, 0x7b, 0xb3, 0x81, 0xe4,
	0x97, 0xe0, 0x24, 0x0f, 0xd5, 0x4c, 0x1a, 0x89, 0xf7, 0xdc, 0x85, 0x9d, 0xc3, 0xf6, 0x5c, 0x4d,
	0x64, 0xc9, 0x45, 0x35, 0xce, 0xe9, 0x1a, 0xf7, 0x60, 0x6b, 0xae, 0x69, 0x56, 0x08, 0x9e, 0x06,
	0xc3, 0x60, 0x14, 0xe5, 0x7d, 0x7b, 0x3d, 0xe3, 0xf8, 0x0c, 0xc0, 0x65, 0x14, 0x55, 0x39, 0xa5,
	0x34, 0x1c, 0x06, 0xa3, 0x38, 0x8f, 0x1d, 0xf2, 0xa9, 0x9c, 0x12, 0x22, 0xf4, 0x54, 0x69, 0x2e,
	0xd3, 0xc8, 0x05, 0xdc, 0x99, 0x1d, 0xc1, 0xfd, 0x4e, 0x6d, 0xad, 0xf0, 0x01, 0x84, 0xf2, 0xca,
	0xd5, 0x1d, 0xe4, 0xa1, 0xbc, 0xb2, 0x77, 0xc1, 0x5d, 0xad, 0x28, 0x0f, 0x05, 0x67, 0x1f, 0x20,
	0xf1, 0x09, 0xc4, 0xef, 0xf0, 0x2d, 0xec, 0x79, 0x33, 0x93, 0x2d, 0xb3, 0xde, 0x96, 0x2d, 0xe0,
	0xe1, 0x98, 0xcc, 0x37, 0xcb, 0xff, 0x28, 0xb4, 0xb9, 0xad, 0xd5, 0xc5, 0x8c, 0x4a, 0x43, 0xbc,
	0x28, 0x4d, 0xd3, 0xaa, 0x46, 0x4e, 0x8d, 0x1f, 0x7b, 0x4c, 0x6e, 0xec, 0x28, 0x77, 0x67, 0xdc,
	0x87, 0xd8, 0xfe, 0x16, 0x5a, 0x2c, 0x28, 0xed, 0xb9, 0xc0, 0xc0, 0x02, 0x5f, 0xc5, 0x82, 0xd8,
	0x9f, 0x00, 0x76, 0x6e, 0x36, 0xd7, 0x0a, 0x5f, 0x41, 0x6f, 0x22, 0xb4, 0x49, 0x83, 0x61, 0x34,
	0x4a, 0x8e, 0x5f, 0x1c, 0x7a, 0x9f, 0x56, 0x69, 0x1e, 0x3e, 0x33, 0x34, 0xcd, 0x1d, 0x1d, 0x0f,
	0x20, 0x31, 0xd2, 0x94, 0x93, 0xc2, 0x56, 0xd7, 0xb5, 0x8e, 0xe0, 0xa0, 0x2f, 0x16, 0x59, 0x12,
	0x2e, 0xe4, 0xbc, 0x32, 0xf5, 0x47, 0x7a, 0xc2, 0x7b, 0x8b, 0x64, 0x47, 0x10, 0xb7, 0x45, 0x6b,
	0x37, 0x82, 0xc6, 0x0d, 0x3b, 0x5b, 0x47, 0x5f, 0x77, 0x66, 0xfb, 0x10, 0x73, 0x9a, 0x90, 0x21,
	0x2b, 0xda, 0x4a, 0x02, 0x7b, 0x0a, 0xd0, 0x04, 0x37, 0xa8, 0xfe, 0x06, 0xe2, 0x31, 0x99, 0xcf,
	0x15, 0xfd, 0x57, 0xef, 0x4d, 0x4d, 0xbf, 0x03, 0x34, 0x99, 0x5a, 0xb5, 0x9b, 0x16, 0x2c, 0x37,
	0xed, 0x36, 0x97, 0x0e, 0x20, 0xf9, 0x29, 0x2a, 0xa1, 0x2f, 0x7d, 0xdc, 0xef, 0x28, 0x34, 0xd0,
	0xa9, 0x39, 0xfe, 0x1d, 0x82, 0x7f, 0x0f, 0xf8, 0x1a, 0xe2, 0x76, 0x67, 0x71, 0xb7, 0x76, 0xa2,
	0xfb, 0x42, 0xb2, 0xc7, 0xeb, 0xa0, 0x56, 0x78, 0x02, 0x83, 0x66, 0xe7, 0x10, 0x6f, 0x30, 0xdc,
	0x2e, 0x67, 0xbb, 0x6b, 0x98, 0x56, 0xf8, 0x16, 0xb6, 0xbb, 0x26, 0xe3, 0x93, 0x8d, 0xce, 0x5f,
	0x67, 0x7b, 0xff, 0xd8, 0x08, 0x7c, 0x09, 0x7d, 0xaf, 0x0c, 0xee, 0x2c, 0x29, 0x5e, 0xe2, 0xec,
	0xd1, 0x0a, 0xe2, 0xe9, 0xde, 0xa0, 0x96, 0xde, 0x9a, 0xd9, 0xd2, 0x97, 0x0e, 0xbe, 0xdb, 0x3a,
	0xf7, 0xa2, 0xfc, 0xe8, 0xbb, 0xbf, 0x8c, 0x93, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x22, 0x46,
	0xa4, 0x70, 0x41, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoClient interface {
	Uploading(ctx context.Context, in *UploadingReq, opts ...grpc.CallOption) (*UploadingResp, error)
	Uploaded(ctx context.Context, in *UploadedReq, opts ...grpc.CallOption) (*UploadedResp, error)
	GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error)
	GetOne(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
}

type videoClient struct {
	cc *grpc.ClientConn
}

func NewVideoClient(cc *grpc.ClientConn) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) Uploading(ctx context.Context, in *UploadingReq, opts ...grpc.CallOption) (*UploadingResp, error) {
	out := new(UploadingResp)
	err := c.cc.Invoke(ctx, "/video.video/uploading", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) Uploaded(ctx context.Context, in *UploadedReq, opts ...grpc.CallOption) (*UploadedResp, error) {
	out := new(UploadedResp)
	err := c.cc.Invoke(ctx, "/video.video/uploaded", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error) {
	out := new(GetVideoListResp)
	err := c.cc.Invoke(ctx, "/video.video/getVideoList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetOne(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error) {
	out := new(GetOneResp)
	err := c.cc.Invoke(ctx, "/video.video/getOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, "/video.video/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
type VideoServer interface {
	Uploading(context.Context, *UploadingReq) (*UploadingResp, error)
	Uploaded(context.Context, *UploadedReq) (*UploadedResp, error)
	GetVideoList(context.Context, *GetVideoListReq) (*GetVideoListResp, error)
	GetOne(context.Context, *GetOneReq) (*GetOneResp, error)
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
}

// UnimplementedVideoServer can be embedded to have forward compatible implementations.
type UnimplementedVideoServer struct {
}

func (*UnimplementedVideoServer) Uploading(ctx context.Context, req *UploadingReq) (*UploadingResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uploading not implemented")
}
func (*UnimplementedVideoServer) Uploaded(ctx context.Context, req *UploadedReq) (*UploadedResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uploaded not implemented")
}
func (*UnimplementedVideoServer) GetVideoList(ctx context.Context, req *GetVideoListReq) (*GetVideoListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoList not implemented")
}
func (*UnimplementedVideoServer) GetOne(ctx context.Context, req *GetOneReq) (*GetOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedVideoServer) Delete(ctx context.Context, req *DeleteReq) (*DeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterVideoServer(s *grpc.Server, srv VideoServer) {
	s.RegisterService(&_Video_serviceDesc, srv)
}

func _Video_Uploading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).Uploading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/Uploading",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).Uploading(ctx, req.(*UploadingReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_Uploaded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).Uploaded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/Uploaded",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).Uploaded(ctx, req.(*UploadedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/GetVideoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoList(ctx, req.(*GetVideoListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetOne(ctx, req.(*GetOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Video_serviceDesc = grpc.ServiceDesc{
	ServiceName: "video.video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "uploading",
			Handler:    _Video_Uploading_Handler,
		},
		{
			MethodName: "uploaded",
			Handler:    _Video_Uploaded_Handler,
		},
		{
			MethodName: "getVideoList",
			Handler:    _Video_GetVideoList_Handler,
		},
		{
			MethodName: "getOne",
			Handler:    _Video_GetOne_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _Video_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
