// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video.proto

package video

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FileId               int64    `protobuf:"varint,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	VideoName            string   `protobuf:"bytes,3,opt,name=video_name,json=videoName,proto3" json:"video_name,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5.png,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateReq) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func (m *CreateReq) GetVideoName() string {
	if m != nil {
		return m.VideoName
	}
	return ""
}

func (m *CreateReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateReq) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type CreateResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResp) Reset()         { *m = CreateResp{} }
func (m *CreateResp) String() string { return proto.CompactTextString(m) }
func (*CreateResp) ProtoMessage()    {}
func (*CreateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{1}
}

func (m *CreateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResp.Unmarshal(m, b)
}
func (m *CreateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResp.Marshal(b, m, deterministic)
}
func (m *CreateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResp.Merge(m, src)
}
func (m *CreateResp) XXX_Size() int {
	return xxx_messageInfo_CreateResp.Size(m)
}
func (m *CreateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResp proto.InternalMessageInfo

func (m *CreateResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CreateResp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetVideoListReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int64    `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoListReq) Reset()         { *m = GetVideoListReq{} }
func (m *GetVideoListReq) String() string { return proto.CompactTextString(m) }
func (*GetVideoListReq) ProtoMessage()    {}
func (*GetVideoListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{2}
}

func (m *GetVideoListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoListReq.Unmarshal(m, b)
}
func (m *GetVideoListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoListReq.Marshal(b, m, deterministic)
}
func (m *GetVideoListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoListReq.Merge(m, src)
}
func (m *GetVideoListReq) XXX_Size() int {
	return xxx_messageInfo_GetVideoListReq.Size(m)
}
func (m *GetVideoListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoListReq proto.InternalMessageInfo

func (m *GetVideoListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetVideoListReq) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetVideoListReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetVideoListReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type GetVideoListResp struct {
	List                 []*GetVideoListRespVideoItem `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalPages           int64                        `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalCount           int64                        `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *GetVideoListResp) Reset()         { *m = GetVideoListResp{} }
func (m *GetVideoListResp) String() string { return proto.CompactTextString(m) }
func (*GetVideoListResp) ProtoMessage()    {}
func (*GetVideoListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{3}
}

func (m *GetVideoListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoListResp.Unmarshal(m, b)
}
func (m *GetVideoListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoListResp.Marshal(b, m, deterministic)
}
func (m *GetVideoListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoListResp.Merge(m, src)
}
func (m *GetVideoListResp) XXX_Size() int {
	return xxx_messageInfo_GetVideoListResp.Size(m)
}
func (m *GetVideoListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoListResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoListResp proto.InternalMessageInfo

func (m *GetVideoListResp) GetList() []*GetVideoListRespVideoItem {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetVideoListResp) GetTotalPages() int64 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *GetVideoListResp) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type GetVideoListRespVideoItem struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVideoListRespVideoItem) Reset()         { *m = GetVideoListRespVideoItem{} }
func (m *GetVideoListRespVideoItem) String() string { return proto.CompactTextString(m) }
func (*GetVideoListRespVideoItem) ProtoMessage()    {}
func (*GetVideoListRespVideoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{3, 0}
}

func (m *GetVideoListRespVideoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVideoListRespVideoItem.Unmarshal(m, b)
}
func (m *GetVideoListRespVideoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVideoListRespVideoItem.Marshal(b, m, deterministic)
}
func (m *GetVideoListRespVideoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVideoListRespVideoItem.Merge(m, src)
}
func (m *GetVideoListRespVideoItem) XXX_Size() int {
	return xxx_messageInfo_GetVideoListRespVideoItem.Size(m)
}
func (m *GetVideoListRespVideoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVideoListRespVideoItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetVideoListRespVideoItem proto.InternalMessageInfo

func (m *GetVideoListRespVideoItem) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetVideoListRespVideoItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetVideoListRespVideoItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetVideoListRespVideoItem) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

type DeleteReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{4}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteResp struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResp) Reset()         { *m = DeleteResp{} }
func (m *DeleteResp) String() string { return proto.CompactTextString(m) }
func (*DeleteResp) ProtoMessage()    {}
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5}
}

func (m *DeleteResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResp.Unmarshal(m, b)
}
func (m *DeleteResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResp.Marshal(b, m, deterministic)
}
func (m *DeleteResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResp.Merge(m, src)
}
func (m *DeleteResp) XXX_Size() int {
	return xxx_messageInfo_DeleteResp.Size(m)
}
func (m *DeleteResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResp proto.InternalMessageInfo

func (m *DeleteResp) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetOneReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneReq) Reset()         { *m = GetOneReq{} }
func (m *GetOneReq) String() string { return proto.CompactTextString(m) }
func (*GetOneReq) ProtoMessage()    {}
func (*GetOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{6}
}

func (m *GetOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneReq.Unmarshal(m, b)
}
func (m *GetOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneReq.Marshal(b, m, deterministic)
}
func (m *GetOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneReq.Merge(m, src)
}
func (m *GetOneReq) XXX_Size() int {
	return xxx_messageInfo_GetOneReq.Size(m)
}
func (m *GetOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneReq proto.InternalMessageInfo

func (m *GetOneReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetOneResp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Desc                 string   `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	FileId               int64    `protobuf:"varint,5.png,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneResp) Reset()         { *m = GetOneResp{} }
func (m *GetOneResp) String() string { return proto.CompactTextString(m) }
func (*GetOneResp) ProtoMessage()    {}
func (*GetOneResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{7}
}

func (m *GetOneResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneResp.Unmarshal(m, b)
}
func (m *GetOneResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneResp.Marshal(b, m, deterministic)
}
func (m *GetOneResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneResp.Merge(m, src)
}
func (m *GetOneResp) XXX_Size() int {
	return xxx_messageInfo_GetOneResp.Size(m)
}
func (m *GetOneResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneResp proto.InternalMessageInfo

func (m *GetOneResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetOneResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetOneResp) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetOneResp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *GetOneResp) GetFileId() int64 {
	if m != nil {
		return m.FileId
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateReq)(nil), "video.createReq")
	proto.RegisterType((*CreateResp)(nil), "video.createResp")
	proto.RegisterType((*GetVideoListReq)(nil), "video.getVideoListReq")
	proto.RegisterType((*GetVideoListResp)(nil), "video.getVideoListResp")
	proto.RegisterType((*GetVideoListRespVideoItem)(nil), "video.getVideoListResp.videoItem")
	proto.RegisterType((*DeleteReq)(nil), "video.deleteReq")
	proto.RegisterType((*DeleteResp)(nil), "video.deleteResp")
	proto.RegisterType((*GetOneReq)(nil), "video.getOneReq")
	proto.RegisterType((*GetOneResp)(nil), "video.getOneResp")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x95, 0x93, 0x36, 0xbb, 0x99, 0x22, 0x58, 0x7c, 0x60, 0xa3, 0xee, 0x22, 0x4a, 0x4e, 0x3d,
	0xb0, 0x7b, 0x58, 0xc4, 0x19, 0x01, 0xa7, 0x4a, 0x08, 0x90, 0x91, 0x38, 0x70, 0x89, 0x42, 0x3d,
	0x54, 0x56, 0xd3, 0x26, 0xad, 0x5d, 0x0e, 0xbd, 0x73, 0xe6, 0xeb, 0xf8, 0x0d, 0xbe, 0x01, 0x8d,
	0x9d, 0xb8, 0x49, 0x68, 0xd1, 0x9e, 0x12, 0xbf, 0x19, 0xfb, 0xf9, 0xbd, 0x37, 0x86, 0xd1, 0x0f,
	0x25, 0xb1, 0xbc, 0xad, 0xb6, 0xa5, 0x29, 0xf9, 0xd0, 0x2e, 0xd2, 0x5f, 0x0c, 0xe2, 0xf9, 0x16,
	0x73, 0x83, 0x02, 0x37, 0xfc, 0x12, 0xce, 0x76, 0x1a, 0xb7, 0x99, 0x92, 0x09, 0x9b, 0xb0, 0x69,
	0x28, 0x22, 0x5a, 0xce, 0x24, 0x15, 0xbe, 0xab, 0x02, 0xa9, 0x10, 0xb8, 0x02, 0x2d, 0x67, 0x92,
	0x3f, 0x05, 0xb0, 0x07, 0x65, 0xeb, 0x7c, 0x85, 0x49, 0x38, 0x61, 0xd3, 0x58, 0xc4, 0x16, 0xf9,
	0x90, 0xaf, 0x90, 0x73, 0x18, 0x48, 0xd4, 0xf3, 0x64, 0x60, 0x0b, 0xf6, 0x9f, 0xb6, 0x38, 0x46,
	0x99, 0xe5, 0x26, 0x19, 0xba, 0x2d, 0x35, 0xf2, 0xc6, 0xa4, 0x2f, 0x9a, 0xb2, 0x40, 0x5d, 0xf1,
	0x87, 0x10, 0x94, 0x4b, 0x7b, 0x99, 0x73, 0x11, 0x94, 0x4b, 0x5a, 0xfb, 0x3b, 0x04, 0x4a, 0xa6,
	0x7b, 0x78, 0xb4, 0x40, 0xf3, 0x85, 0x08, 0xdf, 0x2b, 0x6d, 0xfe, 0x2b, 0xa2, 0x4b, 0x1c, 0xf4,
	0x88, 0xe9, 0xae, 0x55, 0xbe, 0x70, 0x22, 0x42, 0x61, 0xff, 0xf9, 0x15, 0xc4, 0xf4, 0xcd, 0xb4,
	0xda, 0xa3, 0x15, 0x11, 0x8a, 0x73, 0x02, 0x3e, 0xab, 0x3d, 0xa6, 0x7f, 0x18, 0x5c, 0x74, 0xc9,
	0x75, 0xc5, 0x5f, 0xc1, 0xa0, 0x50, 0xda, 0x24, 0x6c, 0x12, 0x4e, 0x47, 0x77, 0xcf, 0x6f, 0x9d,
	0xe7, 0xfd, 0x36, 0x07, 0xcf, 0x0c, 0xae, 0x84, 0x6d, 0xe7, 0xcf, 0x60, 0x64, 0x4a, 0x93, 0x17,
	0x19, 0x9d, 0xae, 0x6b, 0x81, 0x60, 0xa1, 0x4f, 0x84, 0x1c, 0x1a, 0xe6, 0xe5, 0x6e, 0x6d, 0xea,
	0x4b, 0xba, 0x86, 0x77, 0x84, 0x8c, 0x73, 0x88, 0xfd, 0xa1, 0xb5, 0x4d, 0xac, 0xb1, 0x89, 0xb4,
	0xd9, 0x80, 0x9c, 0x68, 0xfb, 0xcf, 0xaf, 0xe1, 0x20, 0xbe, 0x49, 0xae, 0xe3, 0x46, 0x3f, 0xb9,
	0xf4, 0x0a, 0x62, 0x89, 0x05, 0xba, 0x59, 0xe9, 0x51, 0xa4, 0xd7, 0x00, 0x4d, 0xf1, 0xdf, 0xdc,
	0x68, 0xeb, 0x02, 0xcd, 0xc7, 0xf5, 0xd1, 0xad, 0x3f, 0x19, 0x40, 0x53, 0xd5, 0xd5, 0xe9, 0x00,
	0x8f, 0xa9, 0xe8, 0x86, 0x7a, 0x1f, 0x19, 0xed, 0x61, 0x1e, 0xb6, 0x87, 0xf9, 0xee, 0x37, 0x03,
	0xf7, 0x2c, 0xf8, 0x0d, 0x44, 0xee, 0x0c, 0x7e, 0x51, 0x27, 0xe8, 0x1f, 0xc9, 0xf8, 0x71, 0x0f,
	0xd1, 0x15, 0x7f, 0x0d, 0x0f, 0xda, 0x09, 0xf3, 0x27, 0x47, 0x63, 0xdf, 0x8c, 0x2f, 0x4f, 0x8c,
	0x03, 0xf1, 0x39, 0x03, 0x3c, 0x9f, 0x77, 0xcb, 0xf3, 0xb5, 0x1c, 0xba, 0x81, 0xc8, 0x79, 0xed,
	0xdb, 0x7d, 0x2e, 0xbe, 0xfd, 0x10, 0xc6, 0xdb, 0xb3, 0xaf, 0x4e, 0xd6, 0xb7, 0xc8, 0xbe, 0xfd,
	0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xac, 0xea, 0x2f, 0x33, 0x0a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VideoClient is the client API for Video service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VideoClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
	GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error)
	GetOne(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error)
}

type videoClient struct {
	cc *grpc.ClientConn
}

func NewVideoClient(cc *grpc.ClientConn) VideoClient {
	return &videoClient{cc}
}

func (c *videoClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
	out := new(CreateResp)
	err := c.cc.Invoke(ctx, "/video.video/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetVideoList(ctx context.Context, in *GetVideoListReq, opts ...grpc.CallOption) (*GetVideoListResp, error) {
	out := new(GetVideoListResp)
	err := c.cc.Invoke(ctx, "/video.video/getVideoList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) GetOne(ctx context.Context, in *GetOneReq, opts ...grpc.CallOption) (*GetOneResp, error) {
	out := new(GetOneResp)
	err := c.cc.Invoke(ctx, "/video.video/getOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteResp, error) {
	out := new(DeleteResp)
	err := c.cc.Invoke(ctx, "/video.video/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServer is the server API for Video service.
type VideoServer interface {
	Create(context.Context, *CreateReq) (*CreateResp, error)
	GetVideoList(context.Context, *GetVideoListReq) (*GetVideoListResp, error)
	GetOne(context.Context, *GetOneReq) (*GetOneResp, error)
	Delete(context.Context, *DeleteReq) (*DeleteResp, error)
}

// UnimplementedVideoServer can be embedded to have forward compatible implementations.
type UnimplementedVideoServer struct {
}

func (*UnimplementedVideoServer) Create(ctx context.Context, req *CreateReq) (*CreateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedVideoServer) GetVideoList(ctx context.Context, req *GetVideoListReq) (*GetVideoListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVideoList not implemented")
}
func (*UnimplementedVideoServer) GetOne(ctx context.Context, req *GetOneReq) (*GetOneResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (*UnimplementedVideoServer) Delete(ctx context.Context, req *DeleteReq) (*DeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterVideoServer(s *grpc.Server, srv VideoServer) {
	s.RegisterService(&_Video_serviceDesc, srv)
}

func _Video_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetVideoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetVideoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/GetVideoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetVideoList(ctx, req.(*GetVideoListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).GetOne(ctx, req.(*GetOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Video_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/video.video/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Video_serviceDesc = grpc.ServiceDesc{
	ServiceName: "video.video",
	HandlerType: (*VideoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _Video_Create_Handler,
		},
		{
			MethodName: "getVideoList",
			Handler:    _Video_GetVideoList_Handler,
		},
		{
			MethodName: "getOne",
			Handler:    _Video_GetOne_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _Video_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video.proto",
}
