// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type UploadReq struct {
	UserId int    `form:"user_id"`
	Name   string `form:"name"`
	Chunks int    `form:"chunks"`
	Chunk  int    `form:"chunk"`
}

type UploadResp struct {
	Ok bool `json:"ok"`
}
